### ISSUE TITLE
Connect IMUs to raspberry pi

### ISSUE THREAD

**Issue by lucaros95** [bmanga/rtep2019_team18#22]

**Comment by bmanga** [comment]
Things to consider:

- Do we want an application/library or a kernel driver?

- Data will need to be accessed by a remote computer for training and a visualization GUI (can use websockets)

- Interrupt or poll driven?

**Comment by bmanga** [comment]
Going for library using wiringPi for now. Can use a kernel driver later.

Poll driven through timers.
